name: Build Project
run-name: Build exe for Windows Standalone
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-StandaloneWindows
          restore-keys: Library-StandaloneWindows
      - uses: game-ci/unity-builder@v4.2.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows
          versioning: Semantic
          buildName: MajdataPlay
      - run: ls -R
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
